"""English and Russian UI strings, independent of the Windows UI runtime."""

from __future__ import annotations

from typing import Any


DEFAULT_LANGUAGE = "en"
LANGUAGES = ("en", "ru")

MESSAGES = {
    "en": {
        "developed_by": "Developed by",
        "with_codex": "with Codex",
        "repository_link": "Open the project on GitHub",
        "tagline": "Your JetBrains IDE settings stay in place after every update.",
        "settings": "Settings",
        "language": "Language",
        "appearance": "Appearance",
        "theme": "Theme",
        "theme_system": "System default",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "accent": "Accent",
        "apply": "Apply",
        "autostart": "Autostart",
        "enabled": "Enabled",
        "disabled": "Disabled",
        "desktop_shortcut": "Desktop icon",
        "shortcut_enabled": "Enabled",
        "shortcut_disabled": "Disabled",
        "sync_all": "Synchronize all",
        "ides": "IDEs and files",
        "ides_description": "Select a product and choose its .vmoptions file manually.",
        "new_ide": "New association",
        "vmoptions_file": ".vmoptions file",
        "choose_file": "Choose file…",
        "save_ide": "Save association",
        "delete": "Delete",
        "groups": "Option sets",
        "groups_description": "One set can be assigned to multiple IDEs; each IDE can have only one set.",
        "new_group": "New set",
        "group_name": "Set name",
        "group_placeholder": "Example: Common JVM options",
        "assign_ides": "Assign to IDEs",
        "group_lines": "Options — one per line",
        "add_compatibility": "Add plugin compatibility override",
        "save_group": "Save set",
        "editor": "View and edit .vmoptions",
        "editor_description": "Lines from the assigned set are highlighted in green.",
        "sync_now": "Synchronize now",
        "unsaved_prompt": "The contents have changed. Save the file?",
        "discard_file": "Discard changes",
        "save_file": "Save file",
        "trademark_notice": "All trademarks and logos belong to their respective owners. The project author is not affiliated with or a representative of these owners.",
        "never_synced": "not yet performed",
        "last_manual": "Last manual synchronization: {timestamp}",
        "last_auto": "Last automatic restoration: {timestamp}",
        "error": "Error",
        "startup_settings": "Startup settings",
        "desktop_update_failed": "Could not update the desktop icon: {error}",
        "autostart_enable_failed": "Could not enable autostart: {error}",
        "invalid_accent": "The accent color must use the #00FF00 format.",
        "appearance_applied": "Appearance applied.",
        "language_changed": "Interface language changed.",
        "autostart_on_hint": "Files are checked at Windows sign-in without opening the window.",
        "autostart_off_hint": "Automatic restoration at Windows sign-in is disabled.",
        "autostart_on": "Autostart enabled.",
        "autostart_off": "Autostart disabled.",
        "desktop_on_hint": "The shortcut launches the application through start.bat.",
        "desktop_off_hint": "You can launch the application through start.bat or main.py.",
        "desktop_on": "Desktop icon created.",
        "desktop_off": "Desktop icon removed.",
        "select_ide": "Select an IDE.",
        "select_vmoptions": "Choose a file with the .vmoptions extension.",
        "file_not_found": "The specified file does not exist.",
        "duplicate_ide": "An association for {product} already exists.",
        "ide_saved": "IDE association saved.",
        "ide_deleted": "IDE association deleted.",
        "save_open_file_first": "Save or discard the changes in the open file first.",
        "untitled": "Untitled",
        "line_needs_dash": "Each line must start with ‘-’.",
        "line_invalid": "Line {number} must start with ‘-’: {line}",
        "options_required": "Add at least one option line.",
        "name_required": "Enter a name for the option set.",
        "group_saved": "Option set saved.",
        "group_deleted": "Option set deleted.",
        "open_file_failed": "Could not open the file: {error}",
        "missing_lines": "Missing lines from the assigned option set: {count}.",
        "file_saved": ".vmoptions file saved.",
        "save_manual_first": "Save or discard your manual changes first.",
        "lines_added": "Lines added: {count}.",
        "file_synced": "The file is already synchronized.",
        "sync_errors": "Synchronization completed with errors. {details}",
        "sync_incomplete": "Some files could not be processed",
        "files_synced": "Files synchronized: {count}.",
        "all_synced": "All files are already synchronized.",
        "picker_title": "Choose a .vmoptions file",
        "picker_all_files": "All files (*.*)",
        "autostart_windows_only": "Autostart is supported only on Windows.",
        "desktop_windows_only": "Desktop shortcuts are supported only on Windows.",
        "desktop_not_found": "Could not locate the desktop (HRESULT 0x{hresult:08X}).",
        "launcher_not_found": "Launcher file not found: {path}",
        "icon_not_found": "Application icon not found: {path}",
        "shortcut_timeout": "Windows did not finish creating the shortcut within 30 seconds.",
        "shortcut_failed": "Windows could not create the vmoptions Tuner desktop shortcut.",
    },
    "ru": {
        "developed_by": "Разработал",
        "with_codex": "с помощью Codex",
        "repository_link": "Открыть проект на GitHub",
        "tagline": "Ваши настройки JetBrains IDE — на месте после каждого обновления.",
        "settings": "Настройки",
        "language": "Язык",
        "appearance": "Оформление",
        "theme": "Тема",
        "theme_system": "Как в системе",
        "theme_light": "Светлая",
        "theme_dark": "Тёмная",
        "accent": "Акцент",
        "apply": "Применить",
        "autostart": "Автозапуск",
        "enabled": "Включён",
        "disabled": "Выключен",
        "desktop_shortcut": "Иконка на рабочем столе",
        "shortcut_enabled": "Включена",
        "shortcut_disabled": "Выключена",
        "sync_all": "Синхронизировать все",
        "ides": "IDE и файлы",
        "ides_description": "Выберите продукт и укажите его .vmoptions вручную.",
        "new_ide": "Новая связка",
        "vmoptions_file": "Файл .vmoptions",
        "choose_file": "Выбрать файл…",
        "save_ide": "Сохранить связку",
        "delete": "Удалить",
        "groups": "Наборы строк",
        "groups_description": "Один набор можно назначить нескольким IDE; у каждой IDE может быть только один набор.",
        "new_group": "Новый набор",
        "group_name": "Название набора",
        "group_placeholder": "Например: Общие параметры JVM",
        "assign_ides": "Назначить IDE",
        "group_lines": "Строки — по одной на строке",
        "add_compatibility": "Добавить игнорирование совместимости плагинов",
        "save_group": "Сохранить набор",
        "editor": "Просмотр и редактирование .vmoptions",
        "editor_description": "Строки назначенного набора подсвечиваются зелёным.",
        "sync_now": "Синхронизировать сейчас",
        "unsaved_prompt": "Содержимое изменено. Сохранить файл?",
        "discard_file": "Отменить изменения",
        "save_file": "Сохранить файл",
        "trademark_notice": "Все права на товарные знаки и логотипы принадлежат их владельцам. Автор проекта не связан с правообладателями и не является их представителем.",
        "never_synced": "ещё не выполнялась",
        "last_manual": "Последняя ручная синхронизация: {timestamp}",
        "last_auto": "Последнее автоматическое восстановление: {timestamp}",
        "error": "Ошибка",
        "startup_settings": "Настройки запуска",
        "desktop_update_failed": "Не удалось обновить иконку на рабочем столе: {error}",
        "autostart_enable_failed": "Не удалось включить автозапуск: {error}",
        "invalid_accent": "Акцентный цвет должен быть в формате #00FF00.",
        "appearance_applied": "Оформление применено.",
        "language_changed": "Язык интерфейса изменён.",
        "autostart_on_hint": "При входе в Windows файлы проверяются без открытия окна.",
        "autostart_off_hint": "Автоматическое восстановление при входе в Windows отключено.",
        "autostart_on": "Автозапуск включён.",
        "autostart_off": "Автозапуск выключен.",
        "desktop_on_hint": "Ярлык запускает приложение через start.bat.",
        "desktop_off_hint": "Приложение можно запустить через start.bat или main.py.",
        "desktop_on": "Иконка на рабочем столе создана.",
        "desktop_off": "Иконка на рабочем столе удалена.",
        "select_ide": "Выберите IDE.",
        "select_vmoptions": "Выберите файл с расширением .vmoptions.",
        "file_not_found": "Указанный файл не существует.",
        "duplicate_ide": "Для {product} связка уже создана.",
        "ide_saved": "Связка IDE сохранена.",
        "ide_deleted": "Связка IDE удалена.",
        "save_open_file_first": "Сначала сохраните или отмените изменения в открытом файле.",
        "untitled": "Без названия",
        "line_needs_dash": "Каждая строка должна начинаться с ‘-’.",
        "line_invalid": "Строка {number} должна начинаться с ‘-’: {line}",
        "options_required": "Добавьте хотя бы одну строку параметров.",
        "name_required": "Введите название набора.",
        "group_saved": "Набор сохранён.",
        "group_deleted": "Набор удалён.",
        "open_file_failed": "Не удалось открыть файл: {error}",
        "missing_lines": "В файле отсутствуют строки из назначенного набора: {count}.",
        "file_saved": "Файл .vmoptions сохранён.",
        "save_manual_first": "Сначала сохраните или отмените ручные изменения.",
        "lines_added": "Добавлено строк: {count}.",
        "file_synced": "Файл уже синхронизирован.",
        "sync_errors": "Синхронизация завершена с ошибками. {details}",
        "sync_incomplete": "Не все файлы обработаны",
        "files_synced": "Синхронизировано файлов: {count}.",
        "all_synced": "Все файлы уже синхронизированы.",
        "picker_title": "Выберите файл .vmoptions",
        "picker_all_files": "Все файлы (*.*)",
        "autostart_windows_only": "Автозапуск поддерживается только в Windows.",
        "desktop_windows_only": "Ярлык на рабочем столе поддерживается только в Windows.",
        "desktop_not_found": "Не удалось найти рабочий стол (HRESULT 0x{hresult:08X}).",
        "launcher_not_found": "Не найден файл запуска: {path}",
        "icon_not_found": "Не найдена иконка приложения: {path}",
        "shortcut_timeout": "Windows не завершила создание ярлыка за 30 секунд.",
        "shortcut_failed": "Windows не удалось создать ярлык vmoptions Tuner на рабочем столе.",
    },
}

# (WinUI class, named XAML element, Python property, translation key).
# The same bindings update an existing window without rebuilding its controls.
XAML_STRINGS = (
    ("TextBlock", "DevelopedByText", "text", "developed_by"),
    ("TextBlock", "WithCodexText", "text", "with_codex"),
    ("ToolTip", "RepositoryToolTip", "content", "repository_link"),
    ("TextBlock", "TaglineText", "text", "tagline"),
    ("TextBlock", "SettingsTitle", "text", "settings"),
    ("TextBlock", "LanguageLabel", "text", "language"),
    ("TextBlock", "AppearanceLabel", "text", "appearance"),
    ("ComboBox", "ThemePicker", "header", "theme"),
    ("ComboBoxItem", "SystemThemeItem", "content", "theme_system"),
    ("ComboBoxItem", "LightThemeItem", "content", "theme_light"),
    ("ComboBoxItem", "DarkThemeItem", "content", "theme_dark"),
    ("TextBox", "AccentBox", "header", "accent"),
    ("Button", "ApplyAppearanceButton", "content", "apply"),
    ("TextBlock", "AutostartLabel", "text", "autostart"),
    ("ToggleSwitch", "AutostartToggle", "on_content", "enabled"),
    ("ToggleSwitch", "AutostartToggle", "off_content", "disabled"),
    ("TextBlock", "DesktopShortcutLabel", "text", "desktop_shortcut"),
    ("ToggleSwitch", "DesktopShortcutToggle", "on_content", "shortcut_enabled"),
    ("ToggleSwitch", "DesktopShortcutToggle", "off_content", "shortcut_disabled"),
    ("Button", "SyncAllTop", "content", "sync_all"),
    ("Button", "SyncAllBottom", "content", "sync_all"),
    ("TextBlock", "IdesTitle", "text", "ides"),
    ("TextBlock", "IdesDescription", "text", "ides_description"),
    ("Button", "NewIdeButton", "content", "new_ide"),
    ("TextBox", "IdePathBox", "header", "vmoptions_file"),
    ("Button", "ChooseFileButton", "content", "choose_file"),
    ("Button", "SaveIdeButton", "content", "save_ide"),
    ("Button", "DeleteIdeButton", "content", "delete"),
    ("TextBlock", "GroupsTitle", "text", "groups"),
    ("TextBlock", "GroupsDescription", "text", "groups_description"),
    ("Button", "NewGroupButton", "content", "new_group"),
    ("TextBox", "GroupNameBox", "header", "group_name"),
    ("TextBox", "GroupNameBox", "placeholder_text", "group_placeholder"),
    ("TextBlock", "AssignIdesLabel", "text", "assign_ides"),
    ("TextBox", "GroupLinesBox", "header", "group_lines"),
    ("Button", "AddCompatibilityButton", "content", "add_compatibility"),
    ("Button", "SaveGroupButton", "content", "save_group"),
    ("Button", "DeleteGroupButton", "content", "delete"),
    ("TextBlock", "EditorTitle", "text", "editor"),
    ("TextBlock", "EditorDescription", "text", "editor_description"),
    ("Button", "SyncSelectedButton", "content", "sync_now"),
    ("TextBlock", "UnsavedPrompt", "text", "unsaved_prompt"),
    ("Button", "DiscardFileButton", "content", "discard_file"),
    ("Button", "SaveFileButton", "content", "save_file"),
    ("TextBlock", "TrademarkNotice", "text", "trademark_notice"),
)


def normalize_language(value: object) -> str:
    return value if isinstance(value, str) and value in LANGUAGES else DEFAULT_LANGUAGE


def translate(key: str, language: str = DEFAULT_LANGUAGE, **values: Any) -> str:
    return MESSAGES[normalize_language(language)][key].format(**values)


class LocalizedOSError(OSError):
    """Keep an OS error translatable until it reaches the UI."""

    def __init__(self, key: str, **values: Any) -> None:
        self.key = key
        self.values = values
        super().__init__(self.message())

    def message(self, language: str = DEFAULT_LANGUAGE) -> str:
        return translate(self.key, language, **self.values)
